// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: service.proto

package {{.ProjectPackageName}}

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for Foo method
type FooRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Username for authentication
	Username      string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FooRequest) Reset() {
	*x = FooRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FooRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FooRequest) ProtoMessage() {}

func (x *FooRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FooRequest.ProtoReflect.Descriptor instead.
func (*FooRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *FooRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// Response from Foo method
type FooResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Response message
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FooResponse) Reset() {
	*x = FooResponse{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FooResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FooResponse) ProtoMessage() {}

func (x *FooResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FooResponse.ProtoReflect.Descriptor instead.
func (*FooResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *FooResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request for Bar method
type BarRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Username for authentication
	Username      string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BarRequest) Reset() {
	*x = BarRequest{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarRequest) ProtoMessage() {}

func (x *BarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarRequest.ProtoReflect.Descriptor instead.
func (*BarRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *BarRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// Response from Bar method
type BarResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Response message
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BarResponse) Reset() {
	*x = BarResponse{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarResponse) ProtoMessage() {}

func (x *BarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarResponse.ProtoReflect.Descriptor instead.
func (*BarResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *BarResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request for Baz method
type BazRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Username for authentication
	Username      string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BazRequest) Reset() {
	*x = BazRequest{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BazRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BazRequest) ProtoMessage() {}

func (x *BazRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BazRequest.ProtoReflect.Descriptor instead.
func (*BazRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *BazRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// Response from Baz method
type BazResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Response message
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BazResponse) Reset() {
	*x = BazResponse{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BazResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BazResponse) ProtoMessage() {}

func (x *BazResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BazResponse.ProtoReflect.Descriptor instead.
func (*BazResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *BazResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x1aexample_indirect_selection\"(\n" +
	"\n" +
	"FooRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"'\n" +
	"\vFooResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"(\n" +
	"\n" +
	"BarRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"'\n" +
	"\vBarResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"(\n" +
	"\n" +
	"BazRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"'\n" +
	"\vBazResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xa2\x02\n" +
	"\x18ExampleIndirectSelection\x12V\n" +
	"\x03Foo\x12&.example_indirect_selection.FooRequest\x1a'.example_indirect_selection.FooResponse\x12V\n" +
	"\x03Bar\x12&.example_indirect_selection.BarRequest\x1a'.example_indirect_selection.BarResponse\x12V\n" +
	"\x03Baz\x12&.example_indirect_selection.BazRequest\x1a'.example_indirect_selection.BazResponseBPZNgithub.com/something/example-indirect-selection/pkg/example-indirect-selectionb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_service_proto_goTypes = []any{
	(*FooRequest)(nil),  // 0: example_indirect_selection.FooRequest
	(*FooResponse)(nil), // 1: example_indirect_selection.FooResponse
	(*BarRequest)(nil),  // 2: example_indirect_selection.BarRequest
	(*BarResponse)(nil), // 3: example_indirect_selection.BarResponse
	(*BazRequest)(nil),  // 4: example_indirect_selection.BazRequest
	(*BazResponse)(nil), // 5: example_indirect_selection.BazResponse
}
var file_service_proto_depIdxs = []int32{
	0, // 0: example_indirect_selection.ExampleIndirectSelection.Foo:input_type -> example_indirect_selection.FooRequest
	2, // 1: example_indirect_selection.ExampleIndirectSelection.Bar:input_type -> example_indirect_selection.BarRequest
	4, // 2: example_indirect_selection.ExampleIndirectSelection.Baz:input_type -> example_indirect_selection.BazRequest
	1, // 3: example_indirect_selection.ExampleIndirectSelection.Foo:output_type -> example_indirect_selection.FooResponse
	3, // 4: example_indirect_selection.ExampleIndirectSelection.Bar:output_type -> example_indirect_selection.BarResponse
	5, // 5: example_indirect_selection.ExampleIndirectSelection.Baz:output_type -> example_indirect_selection.BazResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
